### ISSUE TITLE
How many GPUs are needed for pre-training?

### ISSUE THREAD

**Issue by jianghaojun** [Pang-Yatian/Point-MAE#19]

**Comment by Pang-Yatian** [comment]
Hi,

For 1K points, one GPU is enough. Two or more could make pre-training faster.

For 8K points, we use 4 GPUs.

**Comment by jianghaojun** [comment]
Thanks for your quick reply!

**Comment by Pang-Yatian** [comment]
Welcome.

**Comment by Zhanlo** [comment]
> Hi,
> 
> For 1K points, one GPU is enough. Two or more could make pre-training faster.
> 
> For 8K points, we use 4 GPUs.
----------------------------------------------------------------------------
Excuse me, does 1k or 8k refer to the number of points in an input point cloud?

**Comment by Zhanlo** [comment]
> Hi,
> 
> For 1K points, one GPU is enough. Two or more could make pre-training faster.
> 
> For 8K points, we use 4 GPUs.

---------------------------------------------------------------------
Excuse me, does 1k or 8k refer to the number of points in an input point cloud? And in the logs provided by you, what GPU configuration does pretrain.log correspond to? Can you explain it in detail? Because I want to know how many GPUs are needed for the corresponding training speed in pretrain.log
