### ISSUE TITLE
Reconstruction Target

### ISSUE THREAD

**Issue by ShoufaChen** [Pang-Yatian/Point-MAE#2]
Hi,

Thanks for your awesome work and opensource.

I have a question about the reconstruction target. Compared with MAE which reconstructs the whole image as output, PointMAE seems to only reconstruct points that are not masked. (with shape mn*k*3). However, it seems that PointMAE reconstructs the whole point from Figure 2. 

I am confused about the reconstruction target. Please tell me if I missed something or had a wrong understanding.

**Comment by Pang-Yatian** [comment]
Hi,

First, MAE only reconstructs masked patches, referring to their paper in Sec. 3 Reconstruction target. Our Point-MAE also reconstructs masked point patches. m is the masking ratio. Therefore, mnxkx3 represents masked point patches. We have clarified the reconstruction target in Section 3.3.

In Figure 2, we visualize the combination point cloud of predicted point patches and visible point patches, in order to compare with the input point cloud.

Sorry for the confusion.

**Comment by auniquesun** [comment]
> 

MAE also reconstructs masked patches since its loss is computed only on the masked parts, then combines predicted and visible patches to produce final images.
