### ISSUE TITLE
(Almost) Identical predicted masked point patches 

### ISSUE THREAD

**Issue by nielsRocholl** [Pang-Yatian/Point-MAE#43]
Hello,

I'm using pointMAE for my research and facing an issue where the predicted masked point patches are nearly identical in every aspect, except their 3D position. All predicted clusters share the same shape, size, and point distribution. I'm working with larger point clouds (10,000 points) than your typical 2,048. Despite adjusting the size and architecture, the issue remains. You can view an example of the predicted point patches here (each patch is colored): [Predicted Points](https://wandb.ai/hyper-alignment/MAE-Toy-Problem-Sweeps/reports/Predicted-Points-24-01-05-09-35-31---Vmlldzo2NDIzNjgy?accessToken=hj8p7pnyk5l0qcrzhiuzewqsd180y79zlrbdhte0j5nx5rsbr9bfmezd0qiusgq6). Any insights on what might be causing this uniformity?

**Comment by Pang-Yatian** [comment]
Hi,

It seems that it is caused by the large point cloud indeed. I guess the points are too "dense" which makes a patch of points contain almost no geometry information, so the predicted patches are almost the same. 

The solution could be 
a).  Downsample the point cloud using FPS, like this https://github.com/Pang-Yatian/Point-MAE/blob/11f4c99f60e2f635e40d23ccaf21ec9aa42705ef/datasets/ModelNetDataset.py#L104

or b). Increase the number of points in a patch by changing group_size in cfg.

You may also need to adjust num_group accordingly. Based on my experience, group_size \* num_group = 2 \* input_num_points works well.

**Comment by nielsRocholl** [comment]
Thanks for your prompt advice! Downsampling effectively resolved the problem. It's even performing well across denser point clouds after setting `group_size * num_group = 2 * input_num_points`. Could you share why this larger setting benefits over a 1:1 ratio for `group_size * num_group` to `input_num_points?`

**Comment by Pang-Yatian** [comment]
Because we use FPS and KNN to divide patches, which may result in (points) overlapping patches. If we set to a 1:1 ratio, some points may not belong to any patches thus losing information.

**Comment by nielsRocholl** [comment]
Aah of course, that makes total sense. Thanks!!
